---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: redis-sentinel
spec:
  type: oci
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-sentinel
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      reconcileStrategy: Revision
      version: "21.1.7"  # Pin to specific version for stability
      sourceRef:
        kind: HelmRepository
        name: redis-sentinel
  values:
    # Enable Redis Sentinel architecture
    architecture: replication
    
    # Authentication configuration
    auth:
      enabled: true
      existingSecret: "redis-sentinel-password"
      existingSecretPasswordKey: "password"
      
    # Redis Sentinel configuration
    sentinel:
      enabled: true
      masterSet: "mymaster"
      quorum: 2
      downAfterMilliseconds: 60000
      failoverTimeout: 180000
      parallelSyncs: 1
      
    # Redis Master configuration
    master:
      count: 1
      service:
        type: ClusterIP
        ports:
          redis: 6379
      persistence:
        enabled: true
        size: 8Gi
        
    # Redis Replica configuration  
    replica:
      replicaCount: 2
      service:
        type: ClusterIP
        ports:
          redis: 6379
      persistence:
        enabled: true
        size: 8Gi
        
    # Metrics configuration (optional)
    metrics:
      enabled: false  # Will be overridden in overlays that need monitoring
      serviceMonitor:
        enabled: false
        interval: 30s
        scrapeTimeout: 10s