---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-password-external
spec:
  # Production-specific configuration
  refreshInterval: 15m  # More frequent refresh for production
  data:
  - secretKey: password
    remoteRef:
      key: "redis/prod/credentials"  # Production secret in AWS
      property: password

---
# Additional ExternalSecret for Elasticsearch production credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: elasticsearch-credentials-external
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: elasticsearch-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
        username: "{{ .username | default "elastic" }}"
  data:
  - secretKey: password
    remoteRef:
      key: "elasticsearch/prod/credentials"
      property: password
  - secretKey: username
    remoteRef:
      key: "elasticsearch/prod/credentials"  
      property: username 