apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to base configuration
resources:
- ../../base

# Patch HelmRelease with production-specific values including monitoring
patches:
- path: helmrelease-patch.yaml

# Environment-specific labels
labels:
- pairs:
    environment: production
    tier: production
    app: elasticsearch

# Production secrets for Elasticsearch
secretGenerator:
- name: elasticsearch-credentials
  behavior: replace
  envs:
  - .env  # Load from .env file (password=your-elastic-password)
  options:
    disableNameSuffixHash: true

# Note: For production, you'll also need to create the elastic-certificates secret manually:
# kubectl create secret generic elastic-certificates --from-file=elastic-certificates.p12

# Namespace for production environment
namespace: elasticsearch-prod 