apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to base configuration
resources:
- ../../base

# Patch HelmRelease with production-specific values including monitoring
patches:
- path: helmrelease-patch.yaml

# Environment-specific labels
labels:
- pairs:
    environment: production
    tier: production
    app: elasticsearch

# Note: Secrets now managed by External Secrets Operator
# The ExternalSecret will create:
# - elasticsearch-credentials (from AWS: elasticsearch/prod/credentials)  
# - redis-sentinel-password (from AWS: redis/prod/credentials)

# Note: For production, you'll also need to create the elastic-certificates secret manually:
# kubectl create secret generic elastic-certificates --from-file=elastic-certificates.p12

# Patch ExternalSecret with production-specific values
patches:
- path: helmrelease-patch.yaml
- path: externalsecret-patch.yaml

# Namespace for production environment
namespace: elasticsearch-prod 