---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-sentinel
spec:
  targetNamespace: redis-sentinel-dev
  values:
    # Development environment overrides
    
    # Sentinel configuration for development
    sentinel:
      masterSet: "redis-dev"  # Different master set name for dev
      quorum: 1  # Lower quorum for dev (only need 1 sentinel to agree)
      
    # Redis Master configuration for development
    master:
      count: 1
      persistence:
        enabled: false  # No persistence in dev for faster startup
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"

    # Redis Replica configuration for development  
    replica:
      replicaCount: 1  # Only 1 replica in dev
      persistence:
        enabled: false  # No persistence in dev
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"  
          cpu: "100m"

    # Disable metrics in development
    metrics:
      enabled: false
      
    # Enable debug logging in development  
    commonConfiguration: |-
      # Enable debug logging
      loglevel verbose 