apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to base configuration
resources:
- ../../base

# Patch HelmRelease with develop-specific values
patches:
- path: helmrelease-patch.yaml

# Environment-specific labels
labels:
- pairs:
    environment: develop
    tier: development

# Override secret generator for develop environment using .env file
secretGenerator:
- name: redis-sentinel-password
  behavior: replace  # Replace the base secret completely
  envs:
  - .env  # Load from .env file
  options:
    disableNameSuffixHash: true

# Namespace for develop environment
namespace: redis-sentinel-dev 