apiVersion: v1
kind: Service
metadata:
  name: fastapi-temporal
  namespace: temporal
  labels:
    app: fastapi-temporal
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: fastapi-temporal 