---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-password-external
spec:
  # Development-specific configuration
  refreshInterval: 60m  # Less frequent refresh for dev
  data:
  - secretKey: password
    remoteRef:
      key: "redis/dev/credentials"  # Development secret in AWS
      property: password 