apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to base configuration
resources:
- ../../base

# Patch HelmRelease and ExternalSecret with develop-specific values
patches:
- path: helmrelease-patch.yaml
- path: externalsecret-patch.yaml

# Environment-specific labels
labels:
- pairs:
    environment: develop
    tier: development
    app: elasticsearch

# Note: Secrets now managed by External Secrets Operator
# pointing to AWS Secrets Manager: redis/dev/credentials

# Namespace for develop environment
namespace: elasticsearch-dev 