apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: uat-

commonLabels:
  environment: uat

patchesStrategicMerge:
- patch-deployment.yaml
- patch-ingressroute.yaml 