apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Resources to include
resources:
- helmrelease.yaml
- secretstore.yaml
- externalsecret.yaml

# Note: Removed secretGenerator as ExternalSecret will create the secret
# The ExternalSecret will create: redis-sentinel-password

# Common metadata
labels:
- pairs:
    app.kubernetes.io/name: elasticsearch  # Updated for Elasticsearch
    app.kubernetes.io/part-of: elasticsearch-cluster 