---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2  # Change to your AWS region
      auth:
        # Option 1: Use IAM Role (recommended for EKS with IRSA)
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
        
        # Option 2: Use AWS Access Keys (not recommended for production)
        # secretRef:
        #   accessKeyIDSecretRef:
        #     name: aws-credentials
        #     key: access-key-id
        #   secretAccessKeySecretRef:
        #     name: aws-credentials
        #     key: secret-access-key

---
# ServiceAccount for External Secrets (if using IRSA)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  annotations:
    # Replace with your actual IAM role ARN
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/external-secrets-role 