---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-sentinel
spec:
  targetNamespace: redis-sentinel-prod
  values:
    # Production environment overrides
    
    # Sentinel configuration for production
    sentinel:
      masterSet: "redis-prod"  # Different master set name for prod
      quorum: 2  # Higher quorum for production reliability
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          interval: 30s
          scrapeTimeout: 10s
          labels:
            prometheus: kube-prometheus-stack
      
    # Redis Master configuration for production
    master:
      count: 1
      persistence:
        enabled: true  # Enable persistence in production
        size: 20Gi
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "500m"

    # Redis Replica configuration for production  
    replica:
      replicaCount: 2  # More replicas in production
      persistence:
        enabled: true  # Enable persistence in production
        size: 20Gi
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "500m"

    # Enable metrics and ServiceMonitor in production
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 30s
        scrapeTimeout: 10s
        labels:
          prometheus: kube-prometheus-stack  # Match your Prometheus operator labels
      
      # Redis Exporter configuration
      image:
        repository: bitnami/redis-exporter
        tag: "1.55.0"
        
      service:
        type: ClusterIP
        port: 9121
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9121"
          
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m" 