apiVersion: v1
kind: Secret
metadata:
  name: cluster-superuser
  namespace: cnpg-system
type: Opaque
stringData:
  username: postgres
  password: superuser-password
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-app-user
  namespace: cnpg-system
type: Opaque
stringData:
  username: appuser
  password: appuser-password 