apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx

resources:
- nginx-deployment.yaml
- nginx-service.yaml
- nginx-ingress-route.yaml

commonLabels:
  app: nginx
  environment: base 