apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patchesStrategicMerge:
- patch-deployment.yaml
- patch-ingressroute.yaml 